### ISSUE TITLE
distutils is going away; code changes needed to migrate

### ISSUE THREAD

**Issue by llimeht** [bumps/bumps#128]
WIth python 3.12, `distutils` will no longer be available, and all uses of distutils will generate runtime errors.

In `bumps`, most uses are for the `distutils.utils.get_platform` function; `sysconfig.get_platform` should be a drop-in replacement for that. The uses in `setup_py2app.py` and `bumps/openmp_ext.py` likely need more work.

Python 3.12-rc1 is already available and it can be added to CI with the `3.12-dev` version.

**Comment by pkienzle** [comment]
Yes, there is a lot of cruft that I ought to clean out :-(

We are no longer shipping a mac app or a windows installer, so setup_py2{app,exe}.py plus master_builder.py are indeed unused. Nothing in extra is part of the current installed set. Installation docs do need to be updated.

If I looked through the git history I might be able to find a version where setup.py triggered a build of dream/compiled.so with openmp support but clearly it is not used in the current version. It can be removed.

**Comment by bmaranville** [comment]
I have removed openmp_ext.py, as suggested.  Python 3.12 tests now pass.
