### ISSUE TITLE
scipy version 1.13.0 causes test breaks: change in scipy.stats.t.ppf

### ISSUE THREAD

**Issue by bmaranville** [bumps/bumps#139]
The tests started spontaneously breaking on old code starting on Apr 2 - after a bit of digging, it might be this change to `scipy.stats`:

https://github.com/scipy/scipy/issues/1603

Here is a reproduction of the difference (`scipy.stats.t.ppf` is used in `bumps.wsolve.LinearModel._interval`)
```python
# with scipy==1.12.0
>>> from scipy.stats import t
>>> t.ppf(0.3, 3)
-0.5843897272635452 
```

```python
# with scipy==1.13.0
>>> from scipy.stats import t
>>> t.ppf(0.3, 3)
-0.5843897274398188
```

This difference is what triggers a change to the calculated value of `ci` in the test, causing the test to fail (in the 9th decimal place, while the test requires that they match to the 14th decimal place)

**Comment by drew-parsons** [comment]
I think this is fixed by
https://github.com/bumps/bumps/commit/af82c757b7cdd78556563af10ee08f013b784002
https://github.com/bumps/bumps/commit/7bb1beb057a0332f51c44e902a8ab6737059ec9b

**Comment by bmaranville** [comment]
Yes, you're right @drew-parsons - closing this now.
