### ISSUE TITLE
Issue with json-difference

### ISSUE THREAD

**Issue by glass-ships** [bumps/bumps#146]
Running `npm run dev` currently fails for refl1d via bumps's `ModelInspect.vue` with:
```
Uncaught SyntaxError: The requested module 'http://localhost:5173/node_modules/json-difference/dist/core/index.js?v=a89b4c51' doesn't provide an export named: 'getDiff' [ModelInspect.vue:5:9](http://localhost:5173/node_modules/bumps-webview-client/src/components/ModelInspect.vue)
```

**Comment by bmaranville** [comment]
It looks like it was actually the previous import that was failing in `dev` mode (`vue-json-viewer`), as it was an IIFE library which `vite build` happily consumed, but which `vite dev` did not.  I swapped it out for a newer library that seems to work well and does the same thing (also has no additional dependencies)
