### ISSUE TITLE
Feature Request - Display number of fitted parameters on the "Summary" tab of the GUI

### ISSUE THREAD

**Issue by alexander-grutter** [bumps/bumps#166]
I would appreciate it if the GUI would display the number of currently fitted parameters somewhere in the summary tab of the GUI. Thank you for coming to my TED talk.

**Comment by pkienzle** [comment]
You can use a negative number for pop to specify the number of chains in a fit (yeah, not an obvious interface choice...).

Doing an ad hoc study on `bumps/doc/examples/peaks/model.py` with 10 fitted parameters on a 160 core server I get:

| pop | pop/var | pop/cpu | time/100 | χ² < 1.0 | time | χ² ≈ 0.871 | time |
|---|---|---|---|---|---|---|---|
| -160 | 16 | 1  | 5 | 223 | 11 | 5000 | 250 |
| -320 | 32 | 2 | 7 | 197 | 14 | 2700 | 190 |
| -800 | 80 | 5 | 8 | 162 | 13 | 3000 | 240 |
| -1600 | 160 | 10 | 13 | 152 | 15 | 1600 | 210 |
| -2400 | 240 | 15 | 14 | 112 | 16 | 1300 | 208 |
| -3200 | 320 | 20 | 17 | 121 |  20 | 2500 | 425 |
| -8000 | 800 | 50 | 21 | 136 | 27  | 1100 | 230 |

The  χ² < 1.0 column gives the median number of steps to reach the target value over five trials. The 0.871 column used a single trial, so the estimate is a lot less reliable.

Time per 100 steps ought to be linear with population size. Clearly there is overhead per iteration inside dream (step proposal, convergence tests, monitor update, checkpoint save) that needs to be improved. This would be less important if the model evaluation time were more expensive.

For the peaks model a population value of -800 looks to be a good compromise between runtime and convergence. Try this on your own models to see if it holds for different number of dimensions.
