### ISSUE TITLE
Does this have anything to do with bumping in machine learning?

### ISSUE THREAD

**Issue by NickKartha** [bumps/bumps#18]
Yeah, sorry for the ignorance but I'm thinking about referencing this repo on my blog. Data fitting, sure. That's important for regressions and classification.

Right now, I'm reading on bumping.
https://statcompute.wordpress.com/2012/06/30/bumping-a-stochastic-search-for-the-best-model/

Does bumps use this concept?!

![selfie-5](https://i.imgur.com/fyrsJGN.png)
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by pkienzle** [comment]
This is a program for doing bayesian uncertainty modeling with Markov Chain Monte Carlo and/or bayesian maximum likelihood estimation using standard optimization algorithms (i.e., non-linear regression).  Problem definitions are set up to be familiar to those in the physical sciences, where measurements have uncertainty.

Bumps is probably not useful for the usual problems in ML, which tend to have too large a parameter space for the algorithms in bumps to search effectively. 

Incidentally, the Tibshirani ref. appears to be from 1999, not 1997:

    Robert Tibshirani & Keith Knight (1999) Model Search by Bootstrap
    “Bumping”, Journal of Computational and Graphical Statistics, 8:4, 671-686, DOI:
    10.1080/10618600.1999.10474842
