### ISSUE TITLE
Saving/reloading problem breaks fitting engine selection

### ISSUE THREAD

**Issue by glass-ships** [bumps/bumps#181]
This one will require a bit of investigation first.

It seems like when saving a problem, then loading it back up, the box allowing to choose a fitting engine breaks and will not allow selection of an engine.

It seems possible that some configuration is missing and not assigned a default value when saving,
so upon loading again, the UI doesn't know how to handle the missing configuration.

Exactly what information is missing is not yet known, will update the story as I do some digging around.

**Comment by bmaranville** [comment]
I am not able to reproduce the issue with the latest version of refl1d (v1.0.0a9) with these steps:

- start refl1d-webview
- from File menu, load problem (.py file)
- from File menu, save problem
- from File menu, load the problem that was just saved (.json or .pickle)

I tried a couple models, one of which could not be serialized to json and write a .pickle file, and the other that did serialize, and in both cases the "Fitting:" settings button still works after the steps above.

**Comment by mdoucet** [comment]
@bmaranville Let me ask Jeehye to try again with the latest version and give us a list of steps to reproduce it.

**Comment by bmaranville** [comment]
I am able to reproduce the problem... I'll get it fixed shortly!
