### ISSUE TITLE
EmbeddedPylab breaks on matplotlib 3.3.1 (latest)

### ISSUE THREAD

**Issue by bmaranville** [bumps/bumps#33]
There was an update to the _pylab_helpers in matplotlib between 3.3.0 and 3.3.1, and the EmbeddedPylab utility in bumps breaks after this change (they removed _activeQue)
see https://github.com/matplotlib/matplotlib/commit/7fcf123051c0b8402f779b68ac9988a2369ed329

**Comment by pkienzle** [comment]
I created a PR for this. It seems to still work on 3.3.0. @bmaranville, do you have a 3.3.1 handy you can test on?

**Comment by bmaranville** [comment]
I do... I tested it and it seems to work, though I suggest one small change to the PR as indicated in the review comment  on the PR.  There may still be a handle leak.
