### ISSUE TITLE
sphinx warnings from api docs

### ISSUE THREAD

**Issue by llimeht** [bumps/bumps#37]
The following warnings are generated by sphinx when building the documentation via sphinx (version 3.2.1 tested)

> …/bumps/doc/api/util.rst:18:<autosummary>:1: WARNING: Inline emphasis start-string without end-string.
> …/bumps/bumps/vfs.py:docstring of bumps.vfs.RealFS.chdir:5: WARNING: Unexpected indentation.
> …/bumps/bumps/vfs.py:docstring of bumps.vfs.RealFS.listdir:6: WARNING: Definition list ends without a blank line; unexpected unindent.
> …/bumps/bumps/vfs.py:docstring of bumps.vfs.RealFS.listdir:8: WARNING: Unexpected indentation.
> …/bumps/bumps/vfs.py:docstring of bumps.vfs.VFS.fs_chdir:5: WARNING: Unexpected indentation.
> …/bumps/bumps/vfs.py:docstring of bumps.vfs.VFS.fs_listdir:6: WARNING: Definition list ends without a blank line; unexpected unindent.
> …/bumps/bumps/vfs.py:docstring of bumps.vfs.VFS.fs_listdir:8: WARNING: Unexpected indentation.

There's a reasonable chance that the HTML output is not quite as desired as a result of these warnings.

As with other projects where we've looked at this, building the documentation on CI with `-W --keep-going -n` would help in the long run.

**Comment by pkienzle** [comment]
I've cleaned up the warnings and added the options to the CI. This should be in the latest release.
