### ISSUE TITLE
chisq is broken for MultiFitProblem when importing garefl models

### ISSUE THREAD

**Issue by hoogerheide** [bumps/bumps#44]
When importing garefl models, a MultiFitProblem is created. MultiFitProblem is based on BaseFitProblem, which has a "fitness" attribute, but this is not the case for MultiFitProblem. So the line if hasattr(self.fitness, 'chisq') fails if "fitness" does not exist for the MultiFitProblem. This shows up when trying to do something like problem.chisq().

This apparently is only an issue for imported garefl models. Testing with a generic set of models combined in a MultiFitProblem did not throw this error.

Oddly, the chisq_str function is calculated differently and does not have this issue.

**Comment by pkienzle** [comment]
> Oddly, the chisq_str function is calculated differently and does not have this issue.

Hence #22.

I fixed refl1d so it no longer calls chisq(). I haven't resolved the chisq() issue yet, but I don't think you will trigger it.
